((lambda (eval environment)
   ((lambda (loop)
      (loop loop null))
    (lambda (loop^ repl)
      (loop^ loop^ (write (eval eval (read) environment))))))

 (lambda (eval^ exp env)
   (if (symbol? exp)
     ((lambda (asq)
         (asq asq exp env))
       (lambda (asq^ e1 env1)
         (if (null? env1)
           null
           (if (eq? e1 (head (head env1)))
             (head (tail (head env1)))
             (asq^ asq^ e1 (tail env1))))))
     (if (symbol? (head exp))
       (if (eq? (head exp) (quote quote))
         (head (tail exp))
         (if (eq? (head exp) (quote if))
           (if (eval^ eval^ (head (tail exp)) env)
             (eval^ eval^ (head (tail (tail exp))) env)
             (eval^ eval^ (head (tail (tail (tail exp)))) env))
           (if (eq? (head exp) (quote lambda))
               exp
             ((lambda (evlist)
                (if (eq? (head exp) (quote apply))
                    ((lambda (fn args)
                       (apply fn args))
                     (eval^ eval^ (head (tail exp)) env)
                     (eval^ eval^ (head (tail (tail exp))) env))
                  ((lambda (fn)
                     (if (list? fn)
                         (eval^ eval^ (list fn (tail exp)) env)
                       (apply fn (evlist evlist (tail exp) env))))
                   (eval^ eval^ (head exp) env))))
              (lambda (evlist^ e1 evargs)
                (if (null? e1)
                    null
                  (list (eval^ eval^ (head e1) env)
                        (evlist^ evlist^ (tail e1) evargs))))))))
       (if (eq? (head (head exp)) (quote lambda))
         ((lambda (env1)
            (eval^ eval^ (head (tail (tail (head exp)))) env1))
          ((lambda (bind names values extenv)
             (bind bind names values extenv))
           (lambda (bind^ names values extenv)
             (if (null? names)
               extenv
               (list (list (head names) (list (eval^ eval^ (head values) env) null))
                     (bind^ bind^ (tail names) (tail values) extenv))))
           (head (tail (head exp)))
           (tail exp)
           env))
         null))))
 (list (list (quote hello) (list (quote carl) null))
 (list (list (quote head) (list head null))
 (list (list (quote tail) (list tail null))
 (list (list (quote list) (list list null))
 (list (list (quote eq?) (list eq? null))
 (list (list (quote list?) (list list? null))
 (list (list (quote symbol?) (list symbol? null))
 (list (list (quote null) (list null null))
 (list (list (quote null?) (list null? null))
 (list (list (quote read) (list read null))
 (list (list (quote write) (list write null)) null)))))))))))
 )
